#!/bin/bash

echo 'Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch
      Server = http://mirror.rackspace.com/archlinux/$repo/os/$arch
      Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist

pacman-key --init \
&& pacman-key --populate \
&& pacman -Syyu --noconfirm \
&& bash -c "rm -rf etc/pacman.d/gnupg/{openpgp-revocs.d/,private-keys-v1.d/,pubring.gpg~,gnupg.S.}*"
